### ISSUE TITLE
Research data structures for efficient slicing of entire dataset

### ISSUE THREAD

**Issue by blairlyons** [simularium/simulariumio#35]
## Use Case
As a computational user, I want to be able to slice AgentData by time and agent in a computationally efficient way.

## Acceptance Criteria
AgentData numpy arrays (or all members of AgentData) are stored internally in a way that allows them to be efficiently sliced, rather than using numpy arrays. 

Can construct AgentData with numpy arrays, lists, or with whatever the internal representation will be (pandas dataframe or xarrays).

## Details
Currently, trajectory data in AgentData is stored in a set of numpy arrays. This makes it more difficult to do filtering operations on the entire dataset. 

Look into how best to do this, maybe with pandas or xarrays.

**Comment by blairlyons** [comment]
Might be relevant to keep in mind https://github.com/simularium/simulariumio/issues/33 while researching

**Comment by ascibisz** [comment]
Summary of research is here: https://docs.google.com/document/d/1FHU7QRxWijQyJEIrJgOstkTWsoAtq7Caph1uDHPUQ9Q/edit#heading=h.wufvdleokyrg
