### ISSUE TITLE
UI-templates for MEDYAN, Cytosim, SpringSaLaD, cellPACK

### ISSUE THREAD

**Issue by blairlyons** [simularium/simulariumio#74]
## Use Case
As a developer of the viewer, I need a template for each converter that specifies how to create a UI to gather required input data.

## Acceptance Criteria
- Each converter has a template for constructing its UI, excluding ReaDDy, PhysiCell, and MCell.

## Details
For auto-converting non-simularium files provided to the viewer, we'll need to collect some additional data from the user through a UI that will depend on the type of file they are converting. SimulariumIO is a good place to keep the specification for each converter so it can be updated with the converter.

ReaDDy, PhysiCell, and MCell don't currently accept opened file data, so they require more development work before we can support autoconversion for them.

**Comment by ascibisz** [comment]
@blairlyons should MD be included in this ticket too?

**Comment by blairlyons** [comment]
> @blairlyons should MD be included in this ticket too?

No, MD requires providing Python objects so it will be a little more complicated
